#!/bin/bash
echo "Start Creation S3 Bucket"
echo "what is $1"
echo "Check what is my bucket name : $1"
export AWS_ACCESS_KEY_ID=AKIA4RVUYOSPZTUUIEVK
export AWS_SECRET_ACCESS_KEY=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
export AWS_DEFAULT_REGION="us-east-1"
/usr/local/bin/aws s3 mb s3://$1/ --region us-east-1
echo " S3 Bucket creation complete"
aws s3 ls

